### ISSUE TITLE
Fayl və Qovluq strukturu

### ISSUE THREAD

**Issue by EldanizAkbar** [AghalarYusublu/PragmatechFoundationProject#1]
Zəhmət olmasa reponda **Layihə** və **Task** qovluqları yarat. Layihəndəki kodları layihə qovluğuna, gündəlik verilən tapşırıqları da task qovluğuna yerləşdir.

**Comment by AghalarYusublu** [comment]
Layihə hələ seçilmədiyinə görə yaratmamışam qovluğu, seçən kimi
yerləşdirəcəm


22 Şub 2021 Pzt 13:32 tarihinde Eldaniz Akbarzada <notifications@github.com>
şunu yazdı:

**Comment by AghalarYusublu** [comment]
qovluqları yaratdım
