### ISSUE TITLE
Branch

### ISSUE THREAD

**Issue by EldanizAkbar** [AghalarYusublu/PragmatechFoundationProject#1]
Zəhmət olmasa kodlarını **main** branch-ında yaz

**Comment by AghalarYusublu** [comment]
salam, mende repoya yukleyende proyekti master branch gelir buna gore ora yuklemisem.

**Comment by AghalarYusublu** [comment]
update edende main branch yazib deyismek olar? problem olmaz?

**Comment by EldanizAkbar** [comment]
Github - ın özündə də edə bilərsən branch dəyişiliyini.  Əgər edə bilməsən aşağıdakı linkdən baxıb edə bilərsən.

https://youtu.be/Q6hbhXsqy74

**Comment by AghalarYusublu** [comment]
default branch deyisdim master etdim. hell oldu

**Comment by EldanizAkbar** [comment]
Branch - ı dəyişib **main** et, sonra **main** branch-ını **default** et
