### ISSUE TITLE
Yazılar tag-in içində yazılmalı

### ISSUE THREAD

**Issue by EldanizAkbar** [AghalarYusublu/PragmatechFoundationProject#2]
https://github.com/AghalarYusublu/PragmatechFoundationProject/blob/53eb0a9a4722fccaa1bd1d16a2b974f5eb7e598a/Plate%20Healthy%20Food%20(Project)/index.html#L67

Layihəndə bəzi yerlərdə div - in içərisində tag istifadə etmədən birbaşa yazı yazmısan. Bu düzgün deyil. O yazıların hər biri bir tag-in içərisində olmalıdır. (məs: span, p)

**Comment by AghalarYusublu** [comment]
tamam düzəliş edəcəm), fikir verməmişəm ora yadımnan çıxıb qalıb elə

**Comment by AghalarYusublu** [comment]
düzəlişlər etdim
