### ISSUE TITLE
Menyudakı linklərin düzəldiməsi

### ISSUE THREAD

**Issue by EldanizAkbar** [AghalarYusublu/PragmatechFoundationProject#3]
https://github.com/AghalarYusublu/PragmatechFoundationProject/blob/cd6313dfcc011a31df05e2ea3040deb9e9222d26/Plate%20Healthy%20Food%20(Project)/index.html#L30

Menyudakı linklərə click işləmir. Zəhmət olmasa onları düzəlt.

**Comment by AghalarYusublu** [comment]
hell oldu.
